const actionTypes = {
  // All poems actions
  FETCH_POEMS_REQUEST: 'FETCH_POEMS_REQUEST',
  FETCH_POEMS_SUCCESS: 'FETCH_POEMS_SUCCESS',
  FETCH_POEMS_FAILURE: 'FETCH_POEMS_FAILURE',

  // Single poem actions
  SELECT_POEM: 'SELECT_POEM',
  DESELECT_POEM: 'DESELECT_POEM',

  DELETE_POEM_REQUEST: 'DELETE_POEM_REQUEST',
  DELETE_POEM_SUCCESS: 'DELETE_POEM_SUCCESS',
  DELETE_POEM_FAILURE: 'DELETE_POEM_FAILURE',

  EDIT_POEM_REQUEST: 'EDIT_POEM_REQUEST',
  EDIT_POEM_SUCCESS: 'EDIT_POEM_SUCCESS',
  EDIT_POEM_FAILURE: 'EDIT_POEM_FAILURE',

  // Modal actions
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',

  // Filters actions
  FILTER_POEMS_BY_YEAR: 'FILTER_POEMS_BY_YEAR',
  FILTER_POEMS_BY_AUTHOR: 'FILTER_POEMS_BY_AUTHOR',
}

export default actionTypes
